# Generated by Django 5.2.13 on 2026-05-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
