# Generated by Django 5.2.13 on 2026-05-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comparison',
            table='comparisons',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='favorites',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='support_tickets',
        ),
    ]
